# Generated by Django 3.1.7 on 2021-03-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordercust', '0004_auto_20210302_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
