# Generated by Django 3.1.7 on 2021-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercust', '0006_auto_20210302_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=False, max_length=80),
        ),
    ]
