# Generated by Django 3.1.7 on 2021-03-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercust', '0008_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(default=False),
        ),
    ]
