# Generated by Django 3.1.7 on 2021-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordercust', '0009_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(default=int, max_length=13),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=300),
        ),
    ]
